### ISSUE TITLE
Support Gstreamer 1.10.0 on Android

### ISSUE THREAD

**Issue by BananaHemic** [BananaHemic/gst-unity-bridge#1]
Currently, this plugin only supports Gstreamer 1.6.4 for Android. Newer Gstreamer versions either fail to compile or at runtime cause the error:

```
GUB: [Quad400] GStreamer encountered a general supporting library error. (gstamcvideodec.c(1013): _gl_sync_render_unlocked (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstAmcVideoDec-OmxExynosAvcDec:amcvideodec-omxexynosavcdec0:
E Unity   : Failed to call Java method: java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
E Unity   : java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
E Unity   :      at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E Unity   :      at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:240)
```

Supporting the newest version will allow increased functionality and performance on Android.

To see how to compile this plugin for Android, please view the [Plugin Readme](https://github.com/BananaHemic/gst-unity-bridge/blob/master/Plugin/readme_plugin.txt)

**Comment by BananaHemic** [comment]
Fixed with 4f81cec4b0485cb7ac1ead4849cb854325550fb8
